# **What is Numpy?**

NumPy is a powerful library for scientific computing in Python. It allows you to work with large arrays and matrices of numerical data, and provides a variety of mathematical operations to perform on them. In this tutorial, we will cover some of the basics of using NumPy.

# **Installation**
NumPy can be installed using pip, the Python package manager:

In [1]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# **Importing NumPy**
Once NumPy is installed, you can import it into your Python program using the import statement:

In [2]:
import numpy as np


# **Creating Arrays**
The basic data structure in NumPy is the array. An array is a collection of elements of the same type, arranged in a grid of rows and columns. You can create an array in NumPy using the array function:

In [3]:
import numpy as np

a = np.array([1, 2, 3])
print(a)


[1 2 3]


In [6]:
#Multidimensional
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)


[[1 2 3]
 [4 5 6]]


# **Array Attributes**
NumPy arrays have several attributes that provide information about the array, such as its shape and data type.

You can get the shape of an array using the shape attribute:

In [7]:
import numpy as np

a = np.array([1, 2, 3])
print(a.shape)

(3,)


In [53]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)

(2, 3)


In [56]:
b = np.array([[1], [4],[6]])
print(b)
print(b.shape)

[[1]
 [4]
 [6]]
(3, 1)


In [8]:
import numpy as np

a = np.array([1, 2, 3])
print(a.dtype)


int64


# **Array Operations**
NumPy provides a variety of mathematical operations that can be performed on arrays. These operations can be performed element-wise, which means the operation is applied to each element of the array.

For example, you can add two arrays together element-wise:

In [11]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)


[5 7 9]


In [57]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5])

c = a + b
print(c)


ValueError: ignored

# **Indexing and Slicing**
You can access elements of an array using indexing and slicing. Indexing allows you to access a single element of an array, while slicing allows you to access a subset of the array.

To access a single element of an array, you can use indexing:

In [12]:
import numpy as np

a = np.array([1, 2, 3])
print(a[0])


1


In [13]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[1:4])


[2 3 4]


In [22]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[::2]) # Output: [1 3 5]

[1 3 5]


# **Broadcasting**
One of the powerful features of NumPy is broadcasting. Broadcasting allows you to perform operations on arrays of different shapes and sizes.

For example, you can add a scalar to an array:

In [14]:
import numpy as np

a = np.array([1, 2, 3])
b = 2

c = a + b
print(c)

[3 4 5]


In [15]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

c = a + b
print(c)


[[2 4 6]
 [5 7 9]]


# **Aggregation Functions**
NumPy provides several aggregation functions that allow you to compute summary statistics on arrays, such as the mean, median, and standard deviation.

For example, you can compute the mean of an array:

In [16]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
mean = np.mean(a)

print(mean)


3.0


In [17]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
median = np.median(a)
stddev = np.std(a)

print(median)
print(stddev)


3.0
1.4142135623730951


# **Array Manipulation**
NumPy provides several functions for manipulating arrays, such as reshaping, concatenating, and splitting arrays.

To reshape an array, you can use the reshape function:

In [18]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape((2, 3))

print(b)


[[1 2 3]
 [4 5 6]]


In [19]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape((2, 4))

print(b)


ValueError: ignored

In [20]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))

print(c)


[1 2 3 4 5 6]


In [21]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b, c = np.split(a, 2)

print(b)
print(c)


[1 2 3]
[4 5 6]


# **Advanced Indexing**
NumPy provides a powerful mechanism called advanced indexing that allows you to select subsets of arrays based on more complex conditions than simple slicing.

There are two types of advanced indexing: integer indexing and Boolean indexing.

# Integer Indexing
With integer indexing, you can select specific elements of an array by specifying their indices as a list or array of integers.

For example, given an array a:

In [23]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [25]:
b = a[[0, 1], [1, 2]]
print(b) 


[2 6]


# **Boolean Indexing**
With Boolean indexing, you can select subsets of an array based on a Boolean condition.

For example, given an array a:

In [26]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [27]:
b = a[a > 5]
print(b) 


[6 7 8 9]


# **Universal Functions**
NumPy provides a wide range of universal functions (ufuncs) that operate on arrays element-wise, meaning they apply the same operation to each element of an array.

Some examples of ufuncs include:

np.sin: computes the sine of each element of an array
np.cos: computes the cosine of each element of an array
np.exp: computes the exponential of each element of an array
np.log: computes the natural logarithm of each element of an array
np.sqrt: computes the square root of each element of an array

In [29]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])


In [30]:
b = np.sin(a)
print(b) 


[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


# **Linear Algebra**
NumPy also provides a comprehensive set of functions for linear algebra operations, such as matrix multiplication, matrix inversion, eigenvalue and eigenvector computations, and more.

For example, given two arrays a and b:

In [31]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])


In [33]:
c = np.dot(a, b)
print(c) 


[[19 22]
 [43 50]]


# **NaN and Infinity**
NumPy provides special values for representing NaN (not a number) and infinity.

To create an array with NaN or infinity values, you can use the np.nan and np.inf functions:

In [34]:
import numpy as np

a = np.array([1, np.nan, np.inf, -np.inf])
print(a) 


[  1.  nan  inf -inf]


In [35]:
print(np.isnan(a))  
print(np.isinf(a))  


[False  True False False]
[False False  True  True]


# **Random Numbers**
NumPy provides a powerful random number generation module, np.random, which allows you to generate random numbers from a variety of distributions.

For example, to generate an array of 10 random numbers from a uniform distribution between 0 and 1, you can use the np.random.rand function:

In [37]:
import numpy as np

a = np.random.rand(10)
print(a) 


[0.58341615 0.79797636 0.89107516 0.67903156 0.24951567 0.90878216
 0.64183231 0.48292122 0.26535763 0.92356892]


In [38]:
b = np.random.randint(10, 30, size=10)
print(b) 


[11 12 25 16 13 14 17 12 11 27]


# **where()**
The np.where function allows you to select elements from two arrays based on a Boolean condition.

For example, given two arrays a and b:

In [39]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])


You can select elements from a where the condition a > 2 is true, and elements from b where the condition a > 2 is false, using the np.where function:

In [40]:
c = np.where(a > 2, a, b)
print(c) 


[10 20  3  4  5]


# **all() and any()**
The np.all() and np.any() functions allow you to check if all or any elements in an array satisfy a certain condition.

For example, to check if all elements in an array are greater than zero:

In [41]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([1, -2, 3, 4, -5])

print(np.all(a > 0))  # Output: True
print(np.all(b > 0))  # Output: False


True
False


In [42]:
print(np.any(a > 0))  # Output: True
print(np.any(b > 0))  # Output: True


True
True


# **Stacking**
NumPy provides several functions for stacking arrays vertically or horizontally.

For example, to stack two arrays vertically:

In [43]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.vstack((a, b))
print(c)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# **Sorting**
NumPy provides several functions for sorting arrays. Let's take a look at np.sort() and np.argsort().

np.sort() can be used to sort an array in ascending order:

In [44]:
import numpy as np

arr = np.array([3, 2, 1, 4, 5])
sorted_arr = np.sort(arr)
print(sorted_arr)


[1 2 3 4 5]


np.argsort() can be used to return the indices that would sort the array:

In [45]:
import numpy as np

arr = np.array([3, 2, 1, 4, 5])
indices = np.argsort(arr)
print(indices)


[2 1 0 3 4]


# **Unique**
np.unique() can be used to find the unique elements in an array:

In [47]:
import numpy as np

arr = np.array([1, 2, 3, 2, 1])
unique_vals, unique_indices = np.unique(arr, return_index=True)
print(unique_vals)
print(unique_indices)


[1 2 3]
[0 1 2]


# **Exporting and Importing**
NumPy provides several functions for exporting and importing arrays to and from files. Let's take a look at np.save() and np.load().

np.save() can be used to save an array to a file:

In [51]:
import numpy as np

arr = np.array([1, 2, 3])
np.save("my_array.npy", arr)


In [52]:
import numpy as np

arr = np.load("my_array.npy")
print(arr)


[1 2 3]
